version: '3'

services:
  rebus.servicehost.manager.testing:
    image: rebus.servicehost.manager.testing
    build:
      context: .
      dockerfile: Rebus.ServiceHost.Manager.Testing\Dockerfile
    depends_on: 
      - rabbitmq
      - elasticsearch
  rebus.servicehost.api.testing:
    image: rebus.servicehost.api.testing
    build:
      context: .
      dockerfile: Rebus.ServiceHost.Api.Testing\Dockerfile
    depends_on: 
      - rabbitmq
      - elasticsearch
  rabbitmq:
    image: micdenny/rabbitmq-windows
  elasticsearch:
    image: p47phoenix/elasticsearch
    build:
      context: ./ElasticSearch
      dockerfile: Dockerfile
    ports:
      - "9200:9200"
  kibana:
    image: p47phoenix/kibana
    build:
      context: ./Kibana
      dockerfile: Dockerfile
    ports:
      - "5601:5601"
    depends_on: 
      - elasticsearch
  cerebro:
    image: p47phoenix/cerebro
    build:
      context: ./Cerebro
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on: 
      - elasticsearch