version: '3'

services:
  rabbitmq:
    image: micdenny/rabbitmq-windows

  rebus.servicehost.manager.testing:
    image: rebus.servicehost.manager.testing
    build:
      context: .
      dockerfile: Rebus.ServiceHost.Manager.Testing\Dockerfile
    depends_on: 
      - rabbitmq

  rebus.servicehost.api.testing:
    image: rebus.servicehost.api.testing
    build:
      context: .
      dockerfile: Rebus.ServiceHost.Api.Testing\Dockerfile
    depends_on: 
      - rabbitmq
